command: [
  "streamlit", 
  "run",
  "app.py"
]

env:
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
  - name: "SERVING_ENDPOINT"
    valueFrom: "https://dbc-6859411e-562c.cloud.databricks.com/serving-endpoints/clinical_trials_agent"
